// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuof1_n2DxPedGnUvKi1V3jD43ysligM8',
    appId: '1:14521645431:web:744deeb13798f4f4f18972',
    messagingSenderId: '14521645431',
    projectId: 'apartment-inspection',
    authDomain: 'apartment-inspection.firebaseapp.com',
    databaseURL: 'https://apartment-inspection-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-inspection.firebasestorage.app',
    measurementId: 'G-HPSJG44Q09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu9svUqJvnA_Js_ong9_HQhuRunpV4QW8',
    appId: '1:14521645431:android:eeb582de5711af4cf18972',
    messagingSenderId: '14521645431',
    projectId: 'apartment-inspection',
    databaseURL: 'https://apartment-inspection-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-inspection.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmJFV32Gt7JsYctQMzahA3Rg9Wv1HJYs',
    appId: '1:14521645431:ios:7c9801195f9b2ac4f18972',
    messagingSenderId: '14521645431',
    projectId: 'apartment-inspection',
    databaseURL: 'https://apartment-inspection-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-inspection.firebasestorage.app',
    iosBundleId: 'com.example.coursevaultApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMmJFV32Gt7JsYctQMzahA3Rg9Wv1HJYs',
    appId: '1:14521645431:ios:7c9801195f9b2ac4f18972',
    messagingSenderId: '14521645431',
    projectId: 'apartment-inspection',
    databaseURL: 'https://apartment-inspection-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-inspection.firebasestorage.app',
    iosBundleId: 'com.example.coursevaultApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuof1_n2DxPedGnUvKi1V3jD43ysligM8',
    appId: '1:14521645431:web:d2e4c228a8b1f4bff18972',
    messagingSenderId: '14521645431',
    projectId: 'apartment-inspection',
    authDomain: 'apartment-inspection.firebaseapp.com',
    databaseURL: 'https://apartment-inspection-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-inspection.firebasestorage.app',
    measurementId: 'G-6T63Z1Q2ML',
  );
}
