// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ZkOheIueWmFxwkN4KuudnJnIohUsRqI',
    appId: '1:1097280974829:web:6bb77936ee20ff5e7a41e4',
    messagingSenderId: '1097280974829',
    projectId: 'coursevault-12ac3',
    authDomain: 'coursevault-12ac3.firebaseapp.com',
    storageBucket: 'coursevault-12ac3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOWmLWIyQAh2XRJlLepUEv_sPYI1pf9fs',
    appId: '1:1097280974829:android:d80a599209d2e30d7a41e4',
    messagingSenderId: '1097280974829',
    projectId: 'coursevault-12ac3',
    storageBucket: 'coursevault-12ac3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGDsBk4nmIElqSBaxDUgBXK55W6Kz8ZPE',
    appId: '1:1097280974829:ios:5c9f5fb8a118bdef7a41e4',
    messagingSenderId: '1097280974829',
    projectId: 'coursevault-12ac3',
    storageBucket: 'coursevault-12ac3.firebasestorage.app',
    iosBundleId: 'com.example.coursevaultApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGDsBk4nmIElqSBaxDUgBXK55W6Kz8ZPE',
    appId: '1:1097280974829:ios:5c9f5fb8a118bdef7a41e4',
    messagingSenderId: '1097280974829',
    projectId: 'coursevault-12ac3',
    storageBucket: 'coursevault-12ac3.firebasestorage.app',
    iosBundleId: 'com.example.coursevaultApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4ZkOheIueWmFxwkN4KuudnJnIohUsRqI',
    appId: '1:1097280974829:web:5547c8ec73dd7baa7a41e4',
    messagingSenderId: '1097280974829',
    projectId: 'coursevault-12ac3',
    authDomain: 'coursevault-12ac3.firebaseapp.com',
    storageBucket: 'coursevault-12ac3.firebasestorage.app',
  );
}
