// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Try web first
    try {
      if (identical(0, 0.0)) {
        // This is for web
        return web;
      }
    } catch (_) {}

    // For Android
    if (Platform.isAndroid) {
      return android;
    }

    // For iOS
    if (Platform.isIOS) {
      return ios;
    }

    // For macOS
    if (Platform.isMacOS) {
      return macos;
    }

    // For Windows
    if (Platform.isWindows) {
      return windows;
    }

    // For Linux
    if (Platform.isLinux) {
      return linux;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions.currentPlatform is not supported for this target platform.',
    );
  }

  // Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForWeb',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'coursevault-demo',
    authDomain: 'coursevault-demo.firebaseapp.com',
    databaseURL: 'https://coursevault-demo.firebaseio.com',
    storageBucket: 'coursevault-demo.appspot.com',
  );

  // Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForAndroid',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'coursevault-demo',
    databaseURL: 'https://coursevault-demo.firebaseio.com',
    storageBucket: 'coursevault-demo.appspot.com',
  );

  // iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForIOS',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'coursevault-demo',
    databaseURL: 'https://coursevault-demo.firebaseio.com',
    storageBucket: 'coursevault-demo.appspot.com',
  );

  // macOS configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForMacOS',
    appId: '1:000000000000:macos:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'coursevault-demo',
    databaseURL: 'https://coursevault-demo.firebaseio.com',
    storageBucket: 'coursevault-demo.appspot.com',
  );

  // Windows configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForWindows',
    appId: '1:000000000000:windows:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'coursevault-demo',
    databaseURL: 'https://coursevault-demo.firebaseio.com',
    storageBucket: 'coursevault-demo.appspot.com',
  );

  // Linux configuration
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForLinux',
    appId: '1:000000000000:linux:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'coursevault-demo',
    databaseURL: 'https://coursevault-demo.firebaseio.com',
    storageBucket: 'coursevault-demo.appspot.com',
  );
}
